export const country_list: {
  ISO: string;
  country_name: string;
  zh_tw_name: string;
  path: string;
}[] = [
  { ISO: "AD", country_name: "Andorra", zh_tw_name: "安道爾", path: "andorra" },
  {
    ISO: "AE",
    country_name: "United Arab Emirates",
    zh_tw_name: "阿拉伯聯合大公國",
    path: "united-arab-emirates",
  },
  {
    ISO: "AF",
    country_name: "Afghanistan",
    zh_tw_name: "阿富汗",
    path: "afghanistan",
  },
  {
    ISO: "AG",
    country_name: "Antigua and Barbuda",
    zh_tw_name: "安地卡及巴布達",
    path: "antigua-and-barbuda",
  },
  {
    ISO: "AI",
    country_name: "Anguilla",
    zh_tw_name: "安圭拉",
    path: "anguilla",
  },
  {
    ISO: "AL",
    country_name: "Albania",
    zh_tw_name: "阿爾巴尼亞",
    path: "albania",
  },
  {
    ISO: "AM",
    country_name: "Armenia",
    zh_tw_name: "亞美尼亞",
    path: "armenia",
  },
  { ISO: "AO", country_name: "Angola", zh_tw_name: "安哥拉", path: "angola" },
  {
    ISO: "AQ",
    country_name: "Antarctica",
    zh_tw_name: "南極洲",
    path: "antarctica",
  },
  {
    ISO: "AR",
    country_name: "Argentina",
    zh_tw_name: "阿根廷",
    path: "argentina",
  },
  {
    ISO: "AS",
    country_name: "American Samoa",
    zh_tw_name: "美屬薩摩亞",
    path: "american-samoa",
  },
  { ISO: "AT", country_name: "Austria", zh_tw_name: "奧地利", path: "austria" },
  {
    ISO: "AU",
    country_name: "Australia",
    zh_tw_name: "澳洲",
    path: "australia",
  },
  { ISO: "AW", country_name: "Aruba", zh_tw_name: "阿魯巴島", path: "aruba" },
  {
    ISO: "AX",
    country_name: "Åland Islands",
    zh_tw_name: "奧蘭群島",
    path: "åland-islands",
  },
  {
    ISO: "AZ",
    country_name: "Azerbaijan",
    zh_tw_name: "亞塞拜然",
    path: "azerbaijan",
  },
  {
    ISO: "BA",
    country_name: "Bosnia and Herzegovina",
    zh_tw_name: "波士尼亞與赫塞哥維納",
    path: "bosnia-and-herzegovina",
  },
  {
    ISO: "BB",
    country_name: "Barbados",
    zh_tw_name: "巴貝多",
    path: "barbados",
  },
  {
    ISO: "BD",
    country_name: "Bangladesh",
    zh_tw_name: "孟加拉",
    path: "bangladesh",
  },
  { ISO: "BE", country_name: "Belgium", zh_tw_name: "比利時", path: "belgium" },
  {
    ISO: "BF",
    country_name: "Burkina Faso",
    zh_tw_name: "布吉納法索",
    path: "burkina-faso",
  },
  {
    ISO: "BG",
    country_name: "Bulgaria",
    zh_tw_name: "保加利亞",
    path: "bulgaria",
  },
  { ISO: "BH", country_name: "Bahrain", zh_tw_name: "巴林", path: "bahrain" },
  { ISO: "BI", country_name: "Burundi", zh_tw_name: "蒲隆地", path: "burundi" },
  { ISO: "BJ", country_name: "Benin", zh_tw_name: "貝南", path: "benin" },
  {
    ISO: "BL",
    country_name: "Saint Barthélemy",
    zh_tw_name: "聖巴泰勒米島",
    path: "saint-barthélemy",
  },
  { ISO: "BM", country_name: "Bermuda", zh_tw_name: "百慕達", path: "bermuda" },
  {
    ISO: "BN",
    country_name: "Brunei Darussalam",
    zh_tw_name: "汶萊達魯薩蘭國",
    path: "brunei-darussalam",
  },
  {
    ISO: "BO",
    country_name: "Bolivia, Plurinational State of",
    zh_tw_name: "多民族玻利維亞國",
    path: "bolivia,-plurinational-state-of",
  },
  {
    ISO: "BQ",
    country_name: "Bonaire, Sint Eustatius and Saba",
    zh_tw_name: "博內爾島、聖尤斯特歇斯島和薩巴島",
    path: "bonaire,-sint-eustatius-and-saba",
  },
  { ISO: "BR", country_name: "Brazil", zh_tw_name: "巴西", path: "brazil" },
  { ISO: "BS", country_name: "Bahamas", zh_tw_name: "巴哈馬", path: "bahamas" },
  { ISO: "BT", country_name: "Bhutan", zh_tw_name: "不丹", path: "bhutan" },
  {
    ISO: "BV",
    country_name: "Bouvet Island",
    zh_tw_name: "布維島",
    path: "bouvet-island",
  },
  {
    ISO: "BW",
    country_name: "Botswana",
    zh_tw_name: "波札那",
    path: "botswana",
  },
  {
    ISO: "BY",
    country_name: "Belarus",
    zh_tw_name: "白俄羅斯",
    path: "belarus",
  },
  { ISO: "BZ", country_name: "Belize", zh_tw_name: "貝里斯", path: "belize" },
  { ISO: "CA", country_name: "Canada", zh_tw_name: "加拿大", path: "canada" },
  {
    ISO: "CC",
    country_name: "Cocos (Keeling) Islands",
    zh_tw_name: "科科斯（基林）群島",
    path: "cocos-(keeling)-islands",
  },
  {
    ISO: "CD",
    country_name: "Congo, Democratic Republic of the",
    zh_tw_name: "剛果民主共和國",
    path: "congo,-democratic-republic-of-the",
  },
  {
    ISO: "CF",
    country_name: "Central African Republic",
    zh_tw_name: "中非共和國",
    path: "central-african-republic",
  },
  { ISO: "CG", country_name: "Congo", zh_tw_name: "剛果", path: "congo" },
  {
    ISO: "CH",
    country_name: "Switzerland",
    zh_tw_name: "瑞士",
    path: "switzerland",
  },
  {
    ISO: "CI",
    country_name: "Côte d'Ivoire",
    zh_tw_name: "科特迪瓦",
    path: "côte-d'ivoire",
  },
  {
    ISO: "CK",
    country_name: "Cook Islands",
    zh_tw_name: "庫克群島",
    path: "cook-islands",
  },
  { ISO: "CL", country_name: "Chile", zh_tw_name: "智利", path: "chile" },
  {
    ISO: "CM",
    country_name: "Cameroon",
    zh_tw_name: "喀麥隆",
    path: "cameroon",
  },
  { ISO: "CN", country_name: "China", zh_tw_name: "中國", path: "china" },
  {
    ISO: "CO",
    country_name: "Colombia",
    zh_tw_name: "哥倫比亞",
    path: "colombia",
  },
  {
    ISO: "CR",
    country_name: "Costa Rica",
    zh_tw_name: "哥斯大黎加",
    path: "costa-rica",
  },
  { ISO: "CU", country_name: "Cuba", zh_tw_name: "古巴", path: "cuba" },
  {
    ISO: "CV",
    country_name: "Cabo Verde",
    zh_tw_name: "維德角",
    path: "cabo-verde",
  },
  {
    ISO: "CW",
    country_name: "Curaçao",
    zh_tw_name: "庫拉索島",
    path: "curaçao",
  },
  {
    ISO: "CX",
    country_name: "Christmas Island",
    zh_tw_name: "聖誕島",
    path: "christmas-island",
  },
  { ISO: "CY", country_name: "Cyprus", zh_tw_name: "賽普勒斯", path: "cyprus" },
  { ISO: "CZ", country_name: "Czechia", zh_tw_name: "捷克", path: "czechia" },
  { ISO: "DE", country_name: "Germany", zh_tw_name: "德國", path: "germany" },
  {
    ISO: "DJ",
    country_name: "Djibouti",
    zh_tw_name: "吉布地",
    path: "djibouti",
  },
  { ISO: "DK", country_name: "Denmark", zh_tw_name: "丹麥", path: "denmark" },
  {
    ISO: "DM",
    country_name: "Dominica",
    zh_tw_name: "多明尼加",
    path: "dominica",
  },
  {
    ISO: "DO",
    country_name: "Dominican Republic",
    zh_tw_name: "多明尼加共和國",
    path: "dominican-republic",
  },
  {
    ISO: "DZ",
    country_name: "Algeria",
    zh_tw_name: "阿爾及利亞",
    path: "algeria",
  },
  { ISO: "EC", country_name: "Ecuador", zh_tw_name: "厄瓜多", path: "ecuador" },
  {
    ISO: "EE",
    country_name: "Estonia",
    zh_tw_name: "愛沙尼亞",
    path: "estonia",
  },
  { ISO: "EG", country_name: "Egypt", zh_tw_name: "埃及", path: "egypt" },
  {
    ISO: "EH",
    country_name: "Western Sahara",
    zh_tw_name: "西撒哈拉",
    path: "western-sahara",
  },
  {
    ISO: "ER",
    country_name: "Eritrea",
    zh_tw_name: "厄利垂亞",
    path: "eritrea",
  },
  { ISO: "ES", country_name: "Spain", zh_tw_name: "西班牙", path: "spain" },
  {
    ISO: "ET",
    country_name: "Ethiopia",
    zh_tw_name: "衣索比亞",
    path: "ethiopia",
  },
  { ISO: "FI", country_name: "Finland", zh_tw_name: "芬蘭", path: "finland" },
  { ISO: "FJ", country_name: "Fiji", zh_tw_name: "斐濟", path: "fiji" },
  {
    ISO: "FK",
    country_name: "Falkland Islands (Malvinas)",
    zh_tw_name: "福克蘭群島（馬爾維納斯）",
    path: "falkland-islands-(malvinas)",
  },
  {
    ISO: "FM",
    country_name: "Micronesia, Federated States of",
    zh_tw_name: "密克羅尼西亞聯邦",
    path: "micronesia,-federated-states-of",
  },
  {
    ISO: "FO",
    country_name: "Faroe Islands",
    zh_tw_name: "法羅群島",
    path: "faroe-islands",
  },
  { ISO: "FR", country_name: "France", zh_tw_name: "法國", path: "france" },
  { ISO: "GA", country_name: "Gabon", zh_tw_name: "加彭", path: "gabon" },
  {
    ISO: "GB",
    // country_name: "United Kingdom of Great Britain and Northern Ireland",
    // zh_tw_name: "大不列顛及北愛爾蘭聯合王國",

    country_name: "UK",
    zh_tw_name: "英國",
    path: "uk",
  },
  {
    ISO: "GD",
    country_name: "Grenada",
    zh_tw_name: "格瑞那達",
    path: "grenada",
  },
  {
    ISO: "GE",
    country_name: "Georgia",
    zh_tw_name: "喬治亞州",
    path: "georgia",
  },
  {
    ISO: "GF",
    country_name: "French Guiana",
    zh_tw_name: "法屬圭亞那",
    path: "french-guiana",
  },
  {
    ISO: "GG",
    country_name: "Guernsey",
    zh_tw_name: "根西島",
    path: "guernsey",
  },
  { ISO: "GH", country_name: "Ghana", zh_tw_name: "迦納", path: "ghana" },
  {
    ISO: "GI",
    country_name: "Gibraltar",
    zh_tw_name: "直布羅陀",
    path: "gibraltar",
  },
  {
    ISO: "GL",
    country_name: "Greenland",
    zh_tw_name: "格陵蘭",
    path: "greenland",
  },
  { ISO: "GM", country_name: "Gambia", zh_tw_name: "甘比亞", path: "gambia" },
  { ISO: "GN", country_name: "Guinea", zh_tw_name: "幾內亞", path: "guinea" },
  {
    ISO: "GP",
    country_name: "Guadeloupe",
    zh_tw_name: "瓜德羅普島",
    path: "guadeloupe",
  },
  {
    ISO: "GQ",
    country_name: "Equatorial Guinea",
    zh_tw_name: "赤道幾內亞",
    path: "equatorial-guinea",
  },
  { ISO: "GR", country_name: "Greece", zh_tw_name: "希臘", path: "greece" },
  {
    ISO: "GS",
    country_name: "South Georgia and the South Sandwich Islands",
    zh_tw_name: "南喬治亞島和南桑威奇群島",
    path: "south-georgia-and-the-south-sandwich-islands",
  },
  {
    ISO: "GT",
    country_name: "Guatemala",
    zh_tw_name: "瓜地馬拉",
    path: "guatemala",
  },
  { ISO: "GU", country_name: "Guam", zh_tw_name: "關島", path: "guam" },
  {
    ISO: "GW",
    country_name: "Guinea-Bissau",
    zh_tw_name: "幾內亞比紹",
    path: "guinea-bissau",
  },
  { ISO: "GY", country_name: "Guyana", zh_tw_name: "蓋亞那", path: "guyana" },
  {
    ISO: "HK",
    country_name: "Hong Kong",
    zh_tw_name: "香港",
    path: "hong-kong",
  },
  {
    ISO: "HM",
    country_name: "Heard Island and McDonald Islands",
    zh_tw_name: "赫德島和麥克唐納群島",
    path: "heard-island-and-mcdonald-islands",
  },
  {
    ISO: "HN",
    country_name: "Honduras",
    zh_tw_name: "宏都拉斯",
    path: "honduras",
  },
  {
    ISO: "HR",
    country_name: "Croatia",
    zh_tw_name: "克羅埃西亞",
    path: "croatia",
  },
  { ISO: "HT", country_name: "Haiti", zh_tw_name: "海地", path: "haiti" },
  { ISO: "HU", country_name: "Hungary", zh_tw_name: "匈牙利", path: "hungary" },
  {
    ISO: "ID",
    country_name: "Indonesia",
    zh_tw_name: "印尼",
    path: "indonesia",
  },
  { ISO: "IE", country_name: "Ireland", zh_tw_name: "愛爾蘭", path: "ireland" },
  { ISO: "IL", country_name: "Israel", zh_tw_name: "以色列", path: "israel" },
  {
    ISO: "IM",
    country_name: "Isle of Man",
    zh_tw_name: "馬恩島",
    path: "isle-of-man",
  },
  { ISO: "IN", country_name: "India", zh_tw_name: "印度", path: "india" },
  {
    ISO: "IO",
    country_name: "British Indian Ocean Territory",
    zh_tw_name: "英屬印度洋領地",
    path: "british-indian-ocean-territory",
  },
  { ISO: "IQ", country_name: "Iraq", zh_tw_name: "伊拉克", path: "iraq" },
  {
    ISO: "IR",
    country_name: "Iran, Islamic Republic of",
    zh_tw_name: "伊朗伊斯蘭共和國",
    path: "iran,-islamic-republic-of",
  },
  { ISO: "IS", country_name: "Iceland", zh_tw_name: "冰島", path: "iceland" },
  { ISO: "IT", country_name: "Italy", zh_tw_name: "義大利", path: "italy" },
  { ISO: "JE", country_name: "Jersey", zh_tw_name: "球衣", path: "jersey" },
  { ISO: "JM", country_name: "Jamaica", zh_tw_name: "牙買加", path: "jamaica" },
  { ISO: "JO", country_name: "Jordan", zh_tw_name: "約旦", path: "jordan" },
  { ISO: "JP", country_name: "Japan", zh_tw_name: "日本", path: "japan" },
  { ISO: "KE", country_name: "Kenya", zh_tw_name: "肯亞", path: "kenya" },
  {
    ISO: "KG",
    country_name: "Kyrgyzstan",
    zh_tw_name: "吉爾吉斯斯坦",
    path: "kyrgyzstan",
  },
  {
    ISO: "KH",
    country_name: "Cambodia",
    zh_tw_name: "柬埔寨",
    path: "cambodia",
  },
  {
    ISO: "KI",
    country_name: "Kiribati",
    zh_tw_name: "吉里巴斯",
    path: "kiribati",
  },
  { ISO: "KM", country_name: "Comoros", zh_tw_name: "葛摩", path: "comoros" },
  {
    ISO: "KN",
    country_name: "Saint Kitts and Nevis",
    zh_tw_name: "聖克里斯多福及尼維斯",
    path: "saint-kitts-and-nevis",
  },
  {
    ISO: "KP",
    country_name: "Korea, Democratic People's Republic of",
    zh_tw_name: "朝鮮民主主義人民共和國",
    path: "korea,-democratic-people's-republic-of",
  },
  {
    ISO: "KR",
    country_name: "Korea, Republic of",
    zh_tw_name: "韓國",
    path: "republic-of-korea",
  },
  { ISO: "KW", country_name: "Kuwait", zh_tw_name: "科威特", path: "kuwait" },
  {
    ISO: "KY",
    country_name: "Cayman Islands",
    zh_tw_name: "開曼群島",
    path: "cayman-islands",
  },
  {
    ISO: "KZ",
    country_name: "Kazakhstan",
    zh_tw_name: "哈薩克",
    path: "kazakhstan",
  },
  {
    ISO: "LA",
    country_name: "Lao People's Democratic Republic",
    zh_tw_name: "寮國人民民主共和國",
    path: "lao-people's-democratic-republic",
  },
  { ISO: "LB", country_name: "Lebanon", zh_tw_name: "黎巴嫩", path: "lebanon" },
  {
    ISO: "LC",
    country_name: "Saint Lucia",
    zh_tw_name: "聖露西亞",
    path: "saint-lucia",
  },
  {
    ISO: "LI",
    country_name: "Liechtenstein",
    zh_tw_name: "列支敦斯登",
    path: "liechtenstein",
  },
  {
    ISO: "LK",
    country_name: "Sri Lanka",
    zh_tw_name: "斯里蘭卡",
    path: "sri-lanka",
  },
  {
    ISO: "LR",
    country_name: "Liberia",
    zh_tw_name: "賴比瑞亞",
    path: "liberia",
  },
  { ISO: "LS", country_name: "Lesotho", zh_tw_name: "賴索托", path: "lesotho" },
  {
    ISO: "LT",
    country_name: "Lithuania",
    zh_tw_name: "立陶宛",
    path: "lithuania",
  },
  {
    ISO: "LU",
    country_name: "Luxembourg",
    zh_tw_name: "盧森堡",
    path: "luxembourg",
  },
  { ISO: "LV", country_name: "Latvia", zh_tw_name: "拉脫維亞", path: "latvia" },
  { ISO: "LY", country_name: "Libya", zh_tw_name: "利比亞", path: "libya" },
  { ISO: "MA", country_name: "Morocco", zh_tw_name: "摩洛哥", path: "morocco" },
  { ISO: "MC", country_name: "Monaco", zh_tw_name: "摩納哥", path: "monaco" },
  {
    ISO: "MD",
    country_name: "Moldova, Republic of",
    zh_tw_name: "摩爾多瓦共和國",
    path: "moldova,-republic-of",
  },
  {
    ISO: "ME",
    country_name: "Montenegro",
    zh_tw_name: "蒙特內哥羅",
    path: "montenegro",
  },
  {
    ISO: "MF",
    country_name: "Saint Martin (French part)",
    zh_tw_name: "聖馬丁島（法文部分）",
    path: "saint-martin-(french-part)",
  },
  {
    ISO: "MG",
    country_name: "Madagascar",
    zh_tw_name: "馬達加斯加",
    path: "madagascar",
  },
  {
    ISO: "MH",
    country_name: "Marshall Islands",
    zh_tw_name: "馬紹爾群島",
    path: "marshall-islands",
  },
  {
    ISO: "MK",
    country_name: "North Macedonia",
    zh_tw_name: "北馬其頓",
    path: "north-macedonia",
  },
  { ISO: "ML", country_name: "Mali", zh_tw_name: "馬裡", path: "mali" },
  { ISO: "MM", country_name: "Myanmar", zh_tw_name: "緬甸", path: "myanmar" },
  { ISO: "MN", country_name: "Mongolia", zh_tw_name: "蒙古", path: "mongolia" },
  { ISO: "MO", country_name: "Macao", zh_tw_name: "澳門", path: "macao" },
  {
    ISO: "MP",
    country_name: "Northern Mariana Islands",
    zh_tw_name: "北馬裡亞納群島",
    path: "northern-mariana-islands",
  },
  {
    ISO: "MQ",
    country_name: "Martinique",
    zh_tw_name: "馬提尼克島",
    path: "martinique",
  },
  {
    ISO: "MR",
    country_name: "Mauritania",
    zh_tw_name: "茅利塔尼亞",
    path: "mauritania",
  },
  {
    ISO: "MS",
    country_name: "Montserrat",
    zh_tw_name: "蒙特塞拉特",
    path: "montserrat",
  },
  { ISO: "MT", country_name: "Malta", zh_tw_name: "馬爾他", path: "malta" },
  {
    ISO: "MU",
    country_name: "Mauritius",
    zh_tw_name: "模里西斯",
    path: "mauritius",
  },
  {
    ISO: "MV",
    country_name: "Maldives",
    zh_tw_name: "馬爾地夫",
    path: "maldives",
  },
  { ISO: "MW", country_name: "Malawi", zh_tw_name: "馬拉威", path: "malawi" },
  { ISO: "MX", country_name: "Mexico", zh_tw_name: "墨西哥", path: "mexico" },
  {
    ISO: "MY",
    country_name: "Malaysia",
    zh_tw_name: "馬來西亞",
    path: "malaysia",
  },
  {
    ISO: "MZ",
    country_name: "Mozambique",
    zh_tw_name: "莫三比克",
    path: "mozambique",
  },
  {
    ISO: "NA",
    country_name: "Namibia",
    zh_tw_name: "納米比亞",
    path: "namibia",
  },
  {
    ISO: "NC",
    country_name: "New Caledonia",
    zh_tw_name: "新喀裡多尼亞",
    path: "new-caledonia",
  },
  { ISO: "NE", country_name: "Niger", zh_tw_name: "尼日", path: "niger" },
  {
    ISO: "NF",
    country_name: "Norfolk Island",
    zh_tw_name: "諾福克島",
    path: "norfolk-island",
  },
  {
    ISO: "NG",
    country_name: "Nigeria",
    zh_tw_name: "奈及利亞",
    path: "nigeria",
  },
  {
    ISO: "NI",
    country_name: "Nicaragua",
    zh_tw_name: "尼加拉瓜",
    path: "nicaragua",
  },
  {
    ISO: "NL",
    country_name: "Netherlands, Kingdom of the",
    zh_tw_name: "荷蘭",
    path: "netherlands,-kingdom-of-the",
  },
  { ISO: "NO", country_name: "Norway", zh_tw_name: "挪威", path: "norway" },
  { ISO: "NP", country_name: "Nepal", zh_tw_name: "尼泊爾", path: "nepal" },
  { ISO: "NR", country_name: "Nauru", zh_tw_name: "諾魯", path: "nauru" },
  { ISO: "NU", country_name: "Niue", zh_tw_name: "紐埃", path: "niue" },
  {
    ISO: "NZ",
    country_name: "New Zealand",
    zh_tw_name: "紐西蘭",
    path: "new-zealand",
  },
  { ISO: "OM", country_name: "Oman", zh_tw_name: "阿曼", path: "oman" },
  { ISO: "PA", country_name: "Panama", zh_tw_name: "巴拿馬", path: "panama" },
  { ISO: "PE", country_name: "Peru", zh_tw_name: "秘魯", path: "peru" },
  {
    ISO: "PF",
    country_name: "French Polynesia",
    zh_tw_name: "法屬玻里尼西亞",
    path: "french-polynesia",
  },
  {
    ISO: "PG",
    country_name: "Papua New Guinea",
    zh_tw_name: "巴布亞紐幾內亞",
    path: "papua-new-guinea",
  },
  {
    ISO: "PH",
    country_name: "Philippines",
    zh_tw_name: "菲律賓",
    path: "philippines",
  },
  {
    ISO: "PK",
    country_name: "Pakistan",
    zh_tw_name: "巴基斯坦",
    path: "pakistan",
  },
  { ISO: "PL", country_name: "Poland", zh_tw_name: "波蘭", path: "poland" },
  {
    ISO: "PM",
    country_name: "Saint Pierre and Miquelon",
    zh_tw_name: "聖皮埃爾和密克隆群島",
    path: "saint-pierre-and-miquelon",
  },
  {
    ISO: "PN",
    country_name: "Pitcairn",
    zh_tw_name: "皮特凱恩",
    path: "pitcairn",
  },
  {
    ISO: "PR",
    country_name: "Puerto Rico",
    zh_tw_name: "波多黎各",
    path: "puerto-rico",
  },
  {
    ISO: "PS",
    country_name: "Palestine, State of",
    zh_tw_name: "巴勒斯坦國",
    path: "palestine,-state-of",
  },
  {
    ISO: "PT",
    country_name: "Portugal",
    zh_tw_name: "葡萄牙",
    path: "portugal",
  },
  { ISO: "PW", country_name: "Palau", zh_tw_name: "帛琉", path: "palau" },
  {
    ISO: "PY",
    country_name: "Paraguay",
    zh_tw_name: "巴拉圭",
    path: "paraguay",
  },
  { ISO: "QA", country_name: "Qatar", zh_tw_name: "卡達", path: "qatar" },
  { ISO: "RE", country_name: "Réunion", zh_tw_name: "團圓", path: "réunion" },
  {
    ISO: "RO",
    country_name: "Romania",
    zh_tw_name: "羅馬尼亞",
    path: "romania",
  },
  { ISO: "RS", country_name: "Serbia", zh_tw_name: "塞爾維亞", path: "serbia" },
  {
    ISO: "RU",
    country_name: "Russian Federation",
    zh_tw_name: "俄羅斯聯邦",
    path: "russian-federation",
  },
  { ISO: "RW", country_name: "Rwanda", zh_tw_name: "盧安達", path: "rwanda" },
  {
    ISO: "SA",
    country_name: "Saudi Arabia",
    zh_tw_name: "沙烏地阿拉伯",
    path: "saudi-arabia",
  },
  {
    ISO: "SB",
    country_name: "Solomon Islands",
    zh_tw_name: "索羅門群島",
    path: "solomon-islands",
  },
  {
    ISO: "SC",
    country_name: "Seychelles",
    zh_tw_name: "塞席爾",
    path: "seychelles",
  },
  { ISO: "SD", country_name: "Sudan", zh_tw_name: "蘇丹", path: "sudan" },
  { ISO: "SE", country_name: "Sweden", zh_tw_name: "瑞典", path: "sweden" },
  {
    ISO: "SG",
    country_name: "Singapore",
    zh_tw_name: "新加坡",
    path: "singapore",
  },
  {
    ISO: "SH",
    country_name: "Saint Helena, Ascension and Tristan da Cunha",
    zh_tw_name: "聖赫勒拿島、阿森松島和特里斯坦達庫尼亞",
    path: "saint-helena,-ascension-and-tristan-da-cunha",
  },
  {
    ISO: "SI",
    country_name: "Slovenia",
    zh_tw_name: "斯洛維尼亞",
    path: "slovenia",
  },
  {
    ISO: "SJ",
    country_name: "Svalbard and Jan Mayen",
    zh_tw_name: "斯瓦爾巴群島和揚馬延島",
    path: "svalbard-and-jan-mayen",
  },
  {
    ISO: "SK",
    country_name: "Slovakia",
    zh_tw_name: "斯洛伐克",
    path: "slovakia",
  },
  {
    ISO: "SL",
    country_name: "Sierra Leone",
    zh_tw_name: "獅子山",
    path: "sierra-leone",
  },
  {
    ISO: "SM",
    country_name: "San Marino",
    zh_tw_name: "聖馬利諾",
    path: "san-marino",
  },
  {
    ISO: "SN",
    country_name: "Senegal",
    zh_tw_name: "塞內加爾",
    path: "senegal",
  },
  {
    ISO: "SO",
    country_name: "Somalia",
    zh_tw_name: "索馬利亞",
    path: "somalia",
  },
  {
    ISO: "SR",
    country_name: "Suriname",
    zh_tw_name: "蘇利南",
    path: "suriname",
  },
  {
    ISO: "SS",
    country_name: "South Sudan",
    zh_tw_name: "南蘇丹",
    path: "south-sudan",
  },
  {
    ISO: "ST",
    country_name: "Sao Tome and Principe",
    zh_tw_name: "聖多美和普林西比",
    path: "sao-tome-and-principe",
  },
  {
    ISO: "SV",
    country_name: "El Salvador",
    zh_tw_name: "薩爾瓦多",
    path: "el-salvador",
  },
  {
    ISO: "SX",
    country_name: "Sint Maarten (Dutch part)",
    zh_tw_name: "聖馬丁島（荷屬部分）",
    path: "sint-maarten-(dutch-part)",
  },
  {
    ISO: "SY",
    country_name: "Syrian Arab Republic",
    zh_tw_name: "阿拉伯敘利亞共和國",
    path: "syrian-arab-republic",
  },
  {
    ISO: "SZ",
    country_name: "Eswatini",
    zh_tw_name: "史瓦帝尼",
    path: "eswatini",
  },
  {
    ISO: "TC",
    country_name: "Turks and Caicos Islands",
    zh_tw_name: "特克斯和凱科斯群島",
    path: "turks-and-caicos-islands",
  },
  { ISO: "TD", country_name: "Chad", zh_tw_name: "查德", path: "chad" },
  {
    ISO: "TF",
    country_name: "French Southern Territories",
    zh_tw_name: "法屬南部領土",
    path: "french-southern-territories",
  },
  { ISO: "TG", country_name: "Togo", zh_tw_name: "多哥", path: "togo" },
  { ISO: "TH", country_name: "Thailand", zh_tw_name: "泰國", path: "thailand" },
  {
    ISO: "TJ",
    country_name: "Tajikistan",
    zh_tw_name: "塔吉克",
    path: "tajikistan",
  },
  { ISO: "TK", country_name: "Tokelau", zh_tw_name: "托克勞", path: "tokelau" },
  {
    ISO: "TL",
    country_name: "Timor-Leste",
    zh_tw_name: "東帝汶",
    path: "timor-leste",
  },
  {
    ISO: "TM",
    country_name: "Turkmenistan",
    zh_tw_name: "土庫曼",
    path: "turkmenistan",
  },
  {
    ISO: "TN",
    country_name: "Tunisia",
    zh_tw_name: "突尼西亞",
    path: "tunisia",
  },
  { ISO: "TO", country_name: "Tonga", zh_tw_name: "東加", path: "tonga" },
  { ISO: "TR", country_name: "Türkiye", zh_tw_name: "土耳其", path: "türkiye" },
  {
    ISO: "TT",
    country_name: "Trinidad and Tobago",
    zh_tw_name: "千里達及托巴哥",
    path: "trinidad-and-tobago",
  },
  { ISO: "TV", country_name: "Tuvalu", zh_tw_name: "吐瓦魯", path: "tuvalu" },
  { ISO: "TW", country_name: "Taiwan", zh_tw_name: "台灣", path: "taiwan" },
  {
    ISO: "TZ",
    country_name: "Tanzania, United Republic of",
    zh_tw_name: "坦尚尼亞聯合共和國",
    path: "tanzania,-united-republic-of",
  },
  { ISO: "UA", country_name: "Ukraine", zh_tw_name: "烏克蘭", path: "ukraine" },
  { ISO: "UG", country_name: "Uganda", zh_tw_name: "烏干達", path: "uganda" },
  {
    ISO: "UM",
    country_name: "United States Minor Outlying Islands",
    zh_tw_name: "美國本土外小島嶼",
    path: "united-states-minor-outlying-islands",
  },
  {
    ISO: "US",
    // country_name: "United States of America",
    country_name: "America",
    zh_tw_name: "美國",
    path: "america",
  },
  { ISO: "UY", country_name: "Uruguay", zh_tw_name: "烏拉圭", path: "uruguay" },
  {
    ISO: "UZ",
    country_name: "Uzbekistan",
    zh_tw_name: "烏茲別克",
    path: "uzbekistan",
  },
  { ISO: "VA", country_name: "Holy See", zh_tw_name: "教廷", path: "holy-see" },
  {
    ISO: "VC",
    country_name: "Saint Vincent and the Grenadines",
    zh_tw_name: "聖文森及格瑞那丁",
    path: "saint-vincent-and-the-grenadines",
  },
  {
    ISO: "VE",
    country_name: "Venezuela, Bolivarian Republic of",
    zh_tw_name: "委內瑞拉玻利瓦爾共和國",
    path: "venezuela,-bolivarian-republic-of",
  },
  {
    ISO: "VG",
    country_name: "Virgin Islands (British)",
    zh_tw_name: "維京群島（英屬）",
    path: "virgin-islands-(british)",
  },
  {
    ISO: "VI",
    country_name: "Virgin Islands (U.S.)",
    zh_tw_name: "維京群島（美國）",
    path: "virgin-islands-(u.s.)",
  },
  { ISO: "VN", country_name: "Viet Nam", zh_tw_name: "越南", path: "viet-nam" },
  { ISO: "VU", country_name: "Vanuatu", zh_tw_name: "萬那杜", path: "vanuatu" },
  {
    ISO: "WF",
    country_name: "Wallis and Futuna",
    zh_tw_name: "瓦利斯和富圖納群島",
    path: "wallis-and-futuna",
  },
  { ISO: "WS", country_name: "Samoa", zh_tw_name: "薩摩亞", path: "samoa" },
  { ISO: "YE", country_name: "Yemen", zh_tw_name: "葉門", path: "yemen" },
  {
    ISO: "YT",
    country_name: "Mayotte",
    zh_tw_name: "馬約特島",
    path: "mayotte",
  },
  {
    ISO: "ZA",
    country_name: "South Africa",
    zh_tw_name: "南非",
    path: "south-africa",
  },
  { ISO: "ZM", country_name: "Zambia", zh_tw_name: "尚比亞", path: "zambia" },
  {
    ISO: "ZW",
    country_name: "Zimbabwe",
    zh_tw_name: "辛巴威",
    path: "zimbabwe",
  },
];

export const form_country_path = (c: string) =>
  c.toLowerCase().split(" ").join("-");
