export const streaming_provider_urls: Record<string, string> = {
    "Netflix": "https://www.netflix.com",
    "Disney Plus": "https://www.disneyplus.com",
    "Amazon Prime Video": "https://www.primevideo.com",
    "HBO Go": "https://www.hbogola.com",
    "Hulu": "https://www.hulu.com",
    "Apple TV Plus": "https://tv.apple.com",
    "YouTube": "https://www.youtube.com",
    "Google Play Movies": "https://play.google.com/store/movies",
    "Viki": "https://www.viki.com",
    "Catchplay": "https://www.catchplay.com",
    "Rakuten TV": "https://tv.rakuten.co.uk",
    "Paramount Plus": "https://www.paramountplus.com",
    "Peacock": "https://www.peacocktv.com",
    "Tubi TV": "https://www.tubitv.com",
    "iQIYI": "https://www.iq.com",
    "LINE TV": "https://www.linetv.tw",
    "KKTV": "https://www.kktv.me",
    "FriDay": "https://www.friday.tw",
  };